### ISSUE TITLE
CallExport: Could not find module in remote process

### ISSUE THREAD

**Issue by roboserg** [ChadSki/SharpNeedle#5] opened 2017-11-05 01:22 UTC
Placed 2x dlls and exe to Debug folder. It manages to inject the bootstrapper.dll, but not the example.dll. Not sure what is wrong. 

Error:
CallExport: Could not find module in remote process

**Comment by ChadSki** [comment] 2017-11-06 22:55
Relevant line of code: https://github.com/ChadSki/SharpNeedle/blob/master/src/Launcher/Injection.cpp#L119

I think that bootstrapper.dll was not successfully injected, which is why Launcher.exe is giving you the error.

Are you attempting to inject into a 64-bit process?

**Comment by ChadSki** [comment] 2017-11-07 21:06
I think this is a dupe of https://github.com/ChadSki/SharpNeedle/issues/1

**Closed as completed by ChadSki** 2017-11-07 21:06 UTC
